import { Config } from '../classes/config.class';

const params = {
  SERVER_PORT: process.env.SERVER_PORT,
  SERVER_HOST: process.env.SERVER_HOST,
  JWT_EXPIRES: process.env.JWT_EXPIRES,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_REFRESH_EXPIRES: process.env.JWT_REFRESH_EXPIRES,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  COOKIE_PASSWORD_SECRET: process.env.COOKIE_PASSWORD_SECRET,

  BASIC_AUTH_LOGIN: process.env.BASIC_AUTH_LOGIN,
  BASIC_AUTH_PASSWORD: process.env.BASIC_AUTH_PASSWORD,

  MDASH_TOKEN: process.env.MDASH_TOKEN,
  MDASH_HOST: process.env.MDASH_HOST,

  DB_URL: process.env.DB_URL,
  DB_TEST_URL: process.env.DB_TEST_URL,

  DEFAULT_LIMIT: process.env.DEFAULT_LIMIT,
  DEFAULT_OFFSET: process.env.DEFAULT_OFFSET,

  WEATHER_APPID: process.env.WEATHER_APPID,

  SUPPORTED_LANGUAGES: process.env.SUPPORTED_LANGUAGES,

  EMAIL: process.env.EMAIL,
  EMAIL_CLIENT_ID: process.env.EMAIL_CLIENT_ID,
  EMAIL_CLIENT_SECRET: process.env.EMAIL_CLIENT_SECRET,
  EMAIL_REFRESH_TOKEN: process.env.EMAIL_REFRESH_TOKEN,

  PROJECT_ID: process.env.PROJECT_ID,
  FILE_BUCKET: process.env.FILE_BUCKET,
  STORAGE_CLIENT_EMAIL: process.env.STORAGE_CLIENT_EMAIL,
  STORAGE_PRIVATE_KEY: process.env.STORAGE_PRIVATE_KEY,

  CLIENT_FIREBASE_PROJECT_NAME: process.env.CLIENT_FIREBASE_PROJECT_NAME,
  CLIENT_FIREBASE_PRIVATE_KEY: process.env.CLIENT_FIREBASE_PRIVATE_KEY,
  CLIENT_FIREBASE_CLIENT_EMAIL: process.env.CLIENT_FIREBASE_CLIENT_EMAIL,
  CLIENT_FIREBASE_DATABASE: process.env.CLIENT_FIREBASE_DATABASE,

  CONFIG_FIREBASE_PROJECT_NAME: process.env.CONFIG_FIREBASE_PROJECT_NAME,
  CONFIG_FIREBASE_PRIVATE_KEY: process.env.CONFIG_FIREBASE_PRIVATE_KEY,
  CONFIG_FIREBASE_CLIENT_EMAIL: process.env.CONFIG_FIREBASE_CLIENT_EMAIL,
  CONFIG_FIREBASE_DATABASE: process.env.CONFIG_FIREBASE_DATABASE,
};

export const config = new Config(params);
